x = 5
print(type(x))


def getDataType(variable):
    print(type(variable))


print("possible data types:")
getDataType("Achoj prdi")
getDataType(20)
getDataType(20.5)
getDataType(True)
getDataType(1j)
getDataType(["apple", "banana", "cherry"])
getDataType(("apple", "banana", "cherry"))
getDataType({"apple", "banana", "cherry"})
getDataType({"name": "John", "age": 36})  # dict = mapa
getDataType(frozenset({"apple", "banana", "cherry"}))
getDataType(range(6))
getDataType(b"Hello")
getDataType(bytearray(5))
getDataType(memoryview(bytes(5)))
getDataType(None)

x = str("Hello World")
print(x)
x = int(20)
print(x)
x = float(20.5)
print(x)
x = complex(1j)
print(x)
x = list(("apple", "banana", "cherry"))
print(x)
x = tuple(("apple", "banana", "cherry"))
print(x)
x = range(6)
print(x)
x = dict(name="John", age=36)
print(x)
x = set(("apple", "banana", "cherry"))
print(x)
x = frozenset(("apple", "banana", "cherry"))
print(x)
x = bool(5)
print(x)
x = bytes(5)
print(x)
x = bytearray(5)
print(x)
x = memoryview(bytes(5))
print(x)
