Rails.application.routes.draw do
  get 'methods/index'
  get 'usefull_syntaxe/prohozeni'
  get 'usefull_syntaxe/nsd'
  get 'usefull_syntaxe/sleepy'
  get 'usefull_syntaxe/random'
  get 'usefull_syntaxe/timing'
  get 'loops/while'
  get 'loops/for'
  get 'excercise/jedna'
  get 'excercise/dva'
  get 'conditions/index'
  root 'app#index'
  get 'test/index'
  get 'test/show'
  get 'app/next'
end
